name: (GitHub Actions) Codecov
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7.x, 3.0.x, 3.1.x]
    steps:
    - uses: actions/checkout@v4
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # プライベートリポジトリで必要
        directory: ./coverage
        name: make-it-easy
        verbose: true
