name: Node.js CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: yarn.lock
    - name: $ yarn install
      run: |
        yarn install --frozen-lockfile
    - name: Jest
      run: |
        yarn test
    - name: Codecov の結果をアップロードする
      uses: codecov/codecov-action@v5
      with:
        directory: ./.coverage
