version: '3.8'
services:
  portainer:
    image: cr.portainer.io/portainer/portainer-ce:2.16.2
    container_name: my_portainer
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    restart: always
