#!/bin/env bash
set -euo pipefail

PUSH_COMMAND_DETAIL=$(ps -ocommand= -p $PPID)
PROHIBITED_OPTIONS='--force|-f'
ERROR_MESSAGE="ERROR: --force や -f オプションの使用は禁じられています。"

echo "push_command: $PUSH_COMMAND_DETAIL"

if [[ $PUSH_COMMAND_DETAIL =~ \s*($PROHIBITED_OPTIONS)\s* ]]; then
  echo $ERROR_MESSAGE

  exit 1
fi

exit 0
