#!/usr/bin/env bash
set -euo pipefail

PUSH_COMMAND_DETAIL=$(ps -ocommand= -p $PPID)
PROHIBITED_COMMANDS=("git push --force" "git push -f")
ERROR_MESSAGE="ERROR: --force や -f オプションの使用は禁じられています。"

echo "[LOG] git push コマンド (pre-push): $PUSH_COMMAND_DETAIL"

for command in "${PROHIBITED_COMMANDS[@]}"; do
  if [[ "$PUSH_COMMAND_DETAIL" == "$command" ]]; then
    echo "$ERROR_MESSAGE"
    exit 1
  fi
done

exit 0
