version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test

workflows:
  main_workflow:
    jobs:
      - build_and_test
