# ~/.config/solargraph/config.yml
# https://solargraph.org/guides/configuration
include:
  - "**/*.rb"
exclude:
  - "**/spec/**/*"
  - "**/test/**/*"
  - "**/vendor/**/*"
  - "**/.bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
# https://github.com/castwide/solargraph/issues/54
# 5000を超えている時点で一般的には多すぎで、実質フリーズ（＝機能しなくなる）の可能性がある
max_files: 5000
