# ゆるすぎるのでいったんコメントアウト
# inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  # TargetRubyVersion: 3.3.7
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - 'db/Schemafile'
    - 'db/schema.rb'
    - 'db/spreadsheet/**/*'
    # - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 180

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# app/lib/mapping.rb:27:9: C: [Correctable] Style/HashEachMethods: Use each_key instead of each and remove the unused _app_group_name block argument.
Style/HashEachMethods:
  Enabled: false

Style/RedundantInitialize:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Max: 52

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/MethodLength:
  Max: 65

Metrics/PerceivedComplexity:
  Max: 17

Metrics/ModuleLength:
  Max: 160

Metrics/AbcSize:
  Max: 30
