#!/bin/sh

# 必要な環境変数
# NICODL_DIR, NICODL_USERNAME, NICODL_PASSWORD
youtube_dl_command_path=$(which youtube-dl)

cd $NICODL_DIR

echo 'ニコニコ動画のビデオのダウンロードを開始します。'

until ${youtube_dl_command_path} --ignore-errors --download-archive .youtube-dl_download-archive --write-all-thumbnails --write-annotations --write-info-json --write-description --write-auto-sub --sleep-interval 15 --max-sleep-interval 30 --format mp4 --username $NICODL_USERNAME --password $NICODL_PASSWORD $1; do continue; done

echo 'ニコニコ動画のビデオのダウンロードが終了しました。'
echo "${NICODL_DIR} にダウンロードされたファイルがあります。"

cd -

exit 0

