#!/bin/sh

# 必要な環境変数
# YTDL_DIR
youtube_dl_command_path=$(which youtube-dl)

cd $YTDL_DIR

echo 'YouTube のビデオのダウンロードを開始します。'

${youtube_dl_command_path} --ignore-errors --download-archive .youtube-dl_download-archive --write-all-thumbnails --write-annotations --write-info-json --write-description --write-auto-sub --sleep-interval 15 --max-sleep-interval 30 --format mp4 $1

echo 'YouTube のビデオのダウンロードが終了しました。'
echo "${YTDL_DIR} にダウンロードされたファイルがあります。"

cd -

exit 0

