#!/bin/bash

# 必要な環境変数
# YTDL_DIR
# yt_dlp_command_path=$(which yt-dlp)
# cd $YTDL_DIR

yt_dlp_command_path=$(which yt-dlp)

echo '[START] YouTube / niconico/ Twitch のビデオのダウンロードを開始します。'

${yt_dlp_command_path} --ignore-errors --download-archive .yt-dlp_download-archive --write-all-thumbnails --write-annotations --write-info-json --write-description --write-auto-sub --sleep-interval 3 --max-sleep-interval 5 --remux-video mkv $1

echo '[END] YouTube / niconico / Twitch のビデオのダウンロードが終了しました。'

cd -

exit 0

